FROM node:current-alpine3.20

WORKDIR /var/www/web

COPY package*.json ./

RUN npm install --legacy-peer-deps

COPY . .

RUN npx prisma generate

RUN npm run build

COPY ./src/utils/reset-password-template.html ./dist/utils/reset-password-template.html

COPY ./src/utils/email-verification.html ./dist/utils/email-verification.html

COPY ./src/utils/invoice-email-template.html ./dist/utils/invoice-email-template.html

COPY ./src/utils/shipping-notification-template.html ./dist/utils/shipping-notification-template.html

EXPOSE 3001 

CMD ["npm", "run", "start:prod"]
