import '../../src/configs/env';
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

export const productVariantSeeder = async () => {
  const variants = [
    // NPK Mutiara 15-15-15 (3 variants)
    {
      id: 'NPK_15_15_15_Premium_1kg',
      productId: 'NPK_15_15_15_Premium',
      weight: '1 kg',
      composition: 'N: 15%, P: 15%, K: 15%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 15000,
    },
    {
      id: 'NPK_15_15_15_Premium_25kg',
      productId: 'NPK_15_15_15_Premium',
      weight: '25 kg',
      composition: 'N: 15%, P: 15%, K: 15%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 350000,
    },
    {
      id: 'NPK_15_15_15_Premium_50kg',
      productId: 'NPK_15_15_15_Premium',
      weight: '50 kg',
      composition: 'N: 15%, P: 15%, K: 15%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 680000,
    },
    // NPK Phonska Plus (2 variants)
    {
      id: 'NPK_Phonska_Plus_25kg',
      productId: 'NPK_Phonska_Plus',
      weight: '25 kg',
      composition: 'N: 15%, P: 15%, K: 15% + Zn',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 320000,
    },
    {
      id: 'NPK_Phonska_Plus_50kg',
      productId: 'NPK_Phonska_Plus',
      weight: '50 kg',
      composition: 'N: 15%, P: 15%, K: 15% + Zn',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 620000,
    },
    // NPK Grower Special (2 variants)
    {
      id: 'NPK_Grower_Special_25kg',
      productId: 'NPK_Grower_Special',
      weight: '25 kg',
      composition: 'N: 20%, P: 10%, K: 10%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 380000,
    },
    {
      id: 'NPK_Grower_Special_50kg',
      productId: 'NPK_Grower_Special',
      weight: '50 kg',
      composition: 'N: 20%, P: 10%, K: 10%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 750000,
    },
    // NPK Booster Buah (3 variants)
    {
      id: 'NPK_Booster_Buah_1kg',
      productId: 'NPK_Booster_Buah',
      weight: '1 kg',
      composition: 'N: 10%, P: 10%, K: 30%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 25000,
    },
    {
      id: 'NPK_Booster_Buah_25kg',
      productId: 'NPK_Booster_Buah',
      weight: '25 kg',
      composition: 'N: 10%, P: 10%, K: 30%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 450000,
    },
    {
      id: 'NPK_Booster_Buah_50kg',
      productId: 'NPK_Booster_Buah',
      weight: '50 kg',
      composition: 'N: 10%, P: 10%, K: 30%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 880000,
    },
    // NPK Compact Slow Release (2 variants)
    {
      id: 'NPK_Compact_SlowRelease_1kg',
      productId: 'NPK_Compact_SlowRelease',
      weight: '1 kg',
      composition: 'N: 18%, P: 9%, K: 12% + TE',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 45000,
    },
    {
      id: 'NPK_Compact_SlowRelease_25kg',
      productId: 'NPK_Compact_SlowRelease',
      weight: '25 kg',
      composition: 'N: 18%, P: 9%, K: 12% + TE',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 950000,
    },
    // Organik Granul Super (2 variants)
    {
      id: 'Organik_Granul_Super_25kg',
      productId: 'Organik_Granul_Super',
      weight: '25 kg',
      composition: 'C-Organik: 15%, NPK Total: 4%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 50000,
    },
    {
      id: 'Organik_Granul_Super_50kg',
      productId: 'Organik_Granul_Super',
      weight: '50 kg',
      composition: 'C-Organik: 15%, NPK Total: 4%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 95000,
    },
    // Kompos Super Matang (2 variants)
    {
      id: 'Kompos_Super_Matang_25kg',
      productId: 'Kompos_Super_Matang',
      weight: '25 kg',
      composition: 'Bahan Organik Pilihan',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 40000,
    },
    {
      id: 'Kompos_Super_Matang_50kg',
      productId: 'Kompos_Super_Matang',
      weight: '50 kg',
      composition: 'Bahan Organik Pilihan',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 75000,
    },
    // Organik Cair Plus Giberelin (2 variants)
    {
      id: 'Organik_Cair_Plus_Giberelin_1L',
      productId: 'Organik_Cair_Plus_Giberelin',
      weight: '1 Liter',
      composition: 'N: 3%, P: 2%, K: 4% + Giberelin',
      packagingId: 'Botol_1L',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 75000,
    },
    {
      id: 'Organik_Cair_Plus_Giberelin_500ml',
      productId: 'Organik_Cair_Plus_Giberelin',
      weight: '500 ml',
      composition: 'N: 3%, P: 2%, K: 4% + Giberelin',
      packagingId: 'Botol_1L', // Assuming 500ml uses a 1L bottle type for simplicity
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 45000,
    },
    // Guano Fosfat Alami (3 variants)
    {
      id: 'Guano_Fosfat_Alami_1kg',
      productId: 'Guano_Fosfat_Alami',
      weight: '1 kg',
      composition: 'P2O5: 25%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 30000,
    },
    {
      id: 'Guano_Fosfat_Alami_25kg',
      productId: 'Guano_Fosfat_Alami',
      weight: '25 kg',
      composition: 'P2O5: 25%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 550000,
    },
    {
      id: 'Guano_Fosfat_Alami_50kg',
      productId: 'Guano_Fosfat_Alami',
      weight: '50 kg',
      composition: 'P2O5: 25%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 1050000,
    },
    // Bio Trichoderma Hayati (2 variants)
    {
      id: 'Bio_Trichoderma_Hayati_1kg',
      productId: 'Bio_Trichoderma_Hayati',
      weight: '1 kg',
      composition: 'Trichoderma sp. 10^6 cfu/gram',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 60000,
    },
    {
      id: 'Bio_Trichoderma_Hayati_500g',
      productId: 'Bio_Trichoderma_Hayati',
      weight: '500 g',
      composition: 'Trichoderma sp. 10^6 cfu/gram',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 35000,
    },
    // Mikroba Rhizobium Plus (2 variants)
    {
      id: 'Mikroba_Rhizobium_Plus_1kg',
      productId: 'Mikroba_Rhizobium_Plus',
      weight: '1 kg',
      composition: 'Rhizobium sp. 10^8 cfu/gram',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 80000,
    },
    {
      id: 'Mikroba_Rhizobium_Plus_250g',
      productId: 'Mikroba_Rhizobium_Plus',
      weight: '250 g',
      composition: 'Rhizobium sp. 10^8 cfu/gram',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 25000,
    },
    // Myco Plus Mikoriza (2 variants)
    {
      id: 'Myco_Plus_Mikoriza_1kg',
      productId: 'Myco_Plus_Mikoriza',
      weight: '1 kg',
      composition: 'Mikoriza spora 1000/gram',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 120000,
    },
    {
      id: 'Myco_Plus_Mikoriza_5kg',
      productId: 'Myco_Plus_Mikoriza',
      weight: '5 kg',
      composition: 'Mikoriza spora 1000/gram',
      packagingId: 'Karung_25kg', // Using a generic bag type
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 550000,
    },
    // Urea Non-Subsidi (2 variants)
    {
      id: 'Urea_NonSubsidi_25kg',
      productId: 'Urea_NonSubsidi',
      weight: '25 kg',
      composition: 'N: 46%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 280000,
    },
    {
      id: 'Urea_NonSubsidi_50kg',
      productId: 'Urea_NonSubsidi',
      weight: '50 kg',
      composition: 'N: 46%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 550000,
    },
    // ZA Amonium Sulfat (2 variants)
    {
      id: 'ZA_Amonium_Sulfat_25kg',
      productId: 'ZA_Amonium_Sulfat',
      weight: '25 kg',
      composition: 'N: 21%, S: 24%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 180000,
    },
    {
      id: 'ZA_Amonium_Sulfat_50kg',
      productId: 'ZA_Amonium_Sulfat',
      weight: '50 kg',
      composition: 'N: 21%, S: 24%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 350000,
    },
    // KCL Kalium Klorida (3 variants)
    {
      id: 'KCL_Kalium_Klorida_1kg',
      productId: 'KCL_Kalium_Klorida',
      weight: '1 kg',
      composition: 'K2O: 60%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 20000,
    },
    {
      id: 'KCL_Kalium_Klorida_25kg',
      productId: 'KCL_Kalium_Klorida',
      weight: '25 kg',
      composition: 'K2O: 60%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 480000,
    },
    {
      id: 'KCL_Kalium_Klorida_50kg',
      productId: 'KCL_Kalium_Klorida',
      weight: '50 kg',
      composition: 'K2O: 60%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 950000,
    },
    // SP-36 Super Fosfat (2 variants)
    {
      id: 'SP36_Super_Fosfat_25kg',
      productId: 'SP36_Super_Fosfat',
      weight: '25 kg',
      composition: 'P2O5: 36%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 220000,
    },
    {
      id: 'SP36_Super_Fosfat_50kg',
      productId: 'SP36_Super_Fosfat',
      weight: '50 kg',
      composition: 'P2O5: 36%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 430000,
    },
    // Mikro Boron Plus (2 variants)
    {
      id: 'Mikro_Boron_Plus_1kg',
      productId: 'Mikro_Boron_Plus',
      weight: '1 kg',
      composition: 'Boron (B): 15%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 50000,
    },
    {
      id: 'Mikro_Boron_Plus_500g',
      productId: 'Mikro_Boron_Plus',
      weight: '500 g',
      composition: 'Boron (B): 15%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 30000,
    },
    // Mikro Fe-Chelate (2 variants)
    {
      id: 'Mikro_Fe_Chelate_1kg',
      productId: 'Mikro_Fe_Chelate',
      weight: '1 kg',
      composition: 'Fe-EDTA: 13%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 150000,
    },
    {
      id: 'Mikro_Fe_Chelate_250g',
      productId: 'Mikro_Fe_Chelate',
      weight: '250 g',
      composition: 'Fe-EDTA: 13%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 45000,
    },
    // Kalsium Nitrat Super (3 variants)
    {
      id: 'Kalsium_Nitrat_Super_1kg',
      productId: 'Kalsium_Nitrat_Super',
      weight: '1 kg',
      composition: 'Ca: 26%, N-NO3: 15.5%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 28000,
    },
    {
      id: 'Kalsium_Nitrat_Super_25kg',
      productId: 'Kalsium_Nitrat_Super',
      weight: '25 kg',
      composition: 'Ca: 26%, N-NO3: 15.5%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 650000,
    },
    {
      id: 'Kalsium_Nitrat_Super_50kg',
      productId: 'Kalsium_Nitrat_Super',
      weight: '50 kg',
      composition: 'Ca: 26%, N-NO3: 15.5%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 1250000,
    },
    // Magnesium Sulfat Epsom (3 variants)
    {
      id: 'Magnesium_Sulfat_Epsom_1kg',
      productId: 'Magnesium_Sulfat_Epsom',
      weight: '1 kg',
      composition: 'MgO: 16%, S: 13%',
      packagingId: 'Sachet_1kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 18000,
    },
    {
      id: 'Magnesium_Sulfat_Epsom_25kg',
      productId: 'Magnesium_Sulfat_Epsom',
      weight: '25 kg',
      composition: 'MgO: 16%, S: 13%',
      packagingId: 'Karung_25kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 400000,
    },
    {
      id: 'Magnesium_Sulfat_Epsom_50kg',
      productId: 'Magnesium_Sulfat_Epsom',
      weight: '50 kg',
      composition: 'MgO: 16%, S: 13%',
      packagingId: 'Karung_50kg',
      imageUrl: '/dashboard/Hero.jpg',
      priceRupiah: 780000,
    },
  ];

  for (const variant of variants) {
    try {
      await prisma.productVariant.create({
        data: variant,
      });
    } catch (error: any) {
      if (error.code === 'P2002') {
        continue;
      }
      throw error;
    }
  }
  console.log('Product variants seeded successfully!');
};
